# Generated by Django 3.2.16 on 2023-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenodo_integration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenodoexperiment',
            name='depo_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
